@startuml
class eps.snabdevanje.promenasnabdevaca.config.MainWebAppInitializer
class eps.snabdevanje.promenasnabdevaca.config.SpringSecurityConfig
class eps.snabdevanje.promenasnabdevaca.config.TransPersistenceJPAConfig
class eps.snabdevanje.promenasnabdevaca.domen.Dokument
class eps.snabdevanje.promenasnabdevaca.domen.GrupaZahteva
class eps.snabdevanje.promenasnabdevaca.domen.Kupac
class eps.snabdevanje.promenasnabdevaca.domen.KupacFizickoLice
class eps.snabdevanje.promenasnabdevaca.domen.KupacPravnoLice
class eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
class eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
class eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaDolazak
class eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaOdlazak
class eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
class eps.snabdevanje.promenasnabdevaca.domen.Status
class eps.snabdevanje.promenasnabdevaca.domen.StatusGrupeZahteva
class eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
class eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
class eps.snabdevanje.promenasnabdevaca.domen.User
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelDokument
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelGrupaZahteva
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelKupac
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelMernoMesto
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelSnabdevac
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTehnickiCentar
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTipDokumenta
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelUser
class eps.snabdevanje.promenasnabdevaca.lazyViews.LazySorterPromenaSnabdevaca
class eps.snabdevanje.promenasnabdevaca.mb.MBDokument
class eps.snabdevanje.promenasnabdevaca.mb.MBFinProvera
class eps.snabdevanje.promenasnabdevaca.mb.MBGrupaZahteva
class eps.snabdevanje.promenasnabdevaca.mb.MBKupac
class eps.snabdevanje.promenasnabdevaca.mb.MBLogin
class eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto
class eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak
class eps.snabdevanje.promenasnabdevaca.mb.MBSnabdevac
class eps.snabdevanje.promenasnabdevaca.mb.MBStatus
class eps.snabdevanje.promenasnabdevaca.mb.MBStatusGrupeZahteva
class eps.snabdevanje.promenasnabdevaca.mb.MBTehnickiCentar
class eps.snabdevanje.promenasnabdevaca.mb.MBTest
class eps.snabdevanje.promenasnabdevaca.mb.MBTipDokumenta
class eps.snabdevanje.promenasnabdevaca.mb.MBUser
class eps.snabdevanje.promenasnabdevaca.service.impl.DokumentServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.GrupaZahtevaServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.KupacServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.MernoMestoServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.PromenaSnabdevacaServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.SnabdevacServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.StatusGrupeZahtevaImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.StatusServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.TehnickiCentarServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.TipDokumentaServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.UserDetailsServiceImpl
class eps.snabdevanje.promenasnabdevaca.service.impl.UserServiceImpl
enum eps.snabdevanje.promenasnabdevaca.domen.enumtype.UserRoleEnum
interface eps.snabdevanje.promenasnabdevaca.repository.DokumentDAO
interface eps.snabdevanje.promenasnabdevaca.repository.GrupaZahtevaDAO
interface eps.snabdevanje.promenasnabdevaca.repository.KupacDAO
interface eps.snabdevanje.promenasnabdevaca.repository.MernoMestoDAO
interface eps.snabdevanje.promenasnabdevaca.repository.PromenaSnabdevacaDAO
interface eps.snabdevanje.promenasnabdevaca.repository.SnabdevacDAO
interface eps.snabdevanje.promenasnabdevaca.repository.StatusDAO
interface eps.snabdevanje.promenasnabdevaca.repository.StatusGrupeZahtevaDAO
interface eps.snabdevanje.promenasnabdevaca.repository.TehnickiCentarDAO
interface eps.snabdevanje.promenasnabdevaca.repository.TipDokumentaDAO
interface eps.snabdevanje.promenasnabdevaca.repository.UserDAO
interface eps.snabdevanje.promenasnabdevaca.service.DokumentService
interface eps.snabdevanje.promenasnabdevaca.service.GrupaZahtevaService
interface eps.snabdevanje.promenasnabdevaca.service.KupacService
interface eps.snabdevanje.promenasnabdevaca.service.MernoMestoService
interface eps.snabdevanje.promenasnabdevaca.service.PromenaSnabdevacaService
interface eps.snabdevanje.promenasnabdevaca.service.SnabdevacService
interface eps.snabdevanje.promenasnabdevaca.service.StatusGrupeZahtevaService
interface eps.snabdevanje.promenasnabdevaca.service.StatusService
interface eps.snabdevanje.promenasnabdevaca.service.TehnickiCentarService
interface eps.snabdevanje.promenasnabdevaca.service.TipDokumentaService
interface eps.snabdevanje.promenasnabdevaca.service.UserService
eps.snabdevanje.promenasnabdevaca.domen.KupacFizickoLice --|> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.domen.KupacPravnoLice --|> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaDolazak --|> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaOdlazak --|> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.domen.User ..> eps.snabdevanje.promenasnabdevaca.domen.enumtype.UserRoleEnum
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelDokument ..> eps.snabdevanje.promenasnabdevaca.domen.Dokument
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelGrupaZahteva ..> eps.snabdevanje.promenasnabdevaca.domen.GrupaZahteva
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelKupac ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelMernoMesto ..> eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaOdlazak
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.Status
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelSnabdevac ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTehnickiCentar ..> eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTipDokumenta ..> eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelUser ..> eps.snabdevanje.promenasnabdevaca.domen.User
eps.snabdevanje.promenasnabdevaca.lazyViews.LazySorterPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.lazyViews.LazySorterPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.lazyViews.LazySorterPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaOdlazak
eps.snabdevanje.promenasnabdevaca.lazyViews.LazySorterPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.lazyViews.LazySorterPromenaSnabdevaca ..> eps.snabdevanje.promenasnabdevaca.domen.Status
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.domen.Dokument
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelDokument
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.repository.DokumentDAO
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.service.DokumentService
eps.snabdevanje.promenasnabdevaca.mb.MBDokument ..> eps.snabdevanje.promenasnabdevaca.service.TipDokumentaService
eps.snabdevanje.promenasnabdevaca.mb.MBFinProvera ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.mb.MBFinProvera ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaOdlazak
eps.snabdevanje.promenasnabdevaca.mb.MBFinProvera ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.mb.MBFinProvera ..> eps.snabdevanje.promenasnabdevaca.service.PromenaSnabdevacaService
eps.snabdevanje.promenasnabdevaca.mb.MBFinProvera ..> eps.snabdevanje.promenasnabdevaca.service.StatusService
eps.snabdevanje.promenasnabdevaca.mb.MBGrupaZahteva ..> eps.snabdevanje.promenasnabdevaca.domen.GrupaZahteva
eps.snabdevanje.promenasnabdevaca.mb.MBGrupaZahteva ..> eps.snabdevanje.promenasnabdevaca.domen.StatusGrupeZahteva
eps.snabdevanje.promenasnabdevaca.mb.MBGrupaZahteva ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelGrupaZahteva
eps.snabdevanje.promenasnabdevaca.mb.MBGrupaZahteva ..> eps.snabdevanje.promenasnabdevaca.service.GrupaZahtevaService
eps.snabdevanje.promenasnabdevaca.mb.MBGrupaZahteva ..> eps.snabdevanje.promenasnabdevaca.service.StatusGrupeZahtevaService
eps.snabdevanje.promenasnabdevaca.mb.MBKupac ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.mb.MBKupac ..> eps.snabdevanje.promenasnabdevaca.domen.KupacFizickoLice
eps.snabdevanje.promenasnabdevaca.mb.MBKupac ..> eps.snabdevanje.promenasnabdevaca.domen.KupacPravnoLice
eps.snabdevanje.promenasnabdevaca.mb.MBKupac ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelKupac
eps.snabdevanje.promenasnabdevaca.mb.MBKupac ..> eps.snabdevanje.promenasnabdevaca.service.KupacService
eps.snabdevanje.promenasnabdevaca.mb.MBLogin ..> eps.snabdevanje.promenasnabdevaca.domen.User
eps.snabdevanje.promenasnabdevaca.mb.MBLogin ..> eps.snabdevanje.promenasnabdevaca.service.UserService
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelMernoMesto
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.service.MernoMestoService
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.service.PromenaSnabdevacaService
eps.snabdevanje.promenasnabdevaca.mb.MBMernoMesto ..> eps.snabdevanje.promenasnabdevaca.service.TehnickiCentarService
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevacaOdlazak
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelPromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.service.GrupaZahtevaService
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.service.KupacService
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.service.PromenaSnabdevacaService
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.service.SnabdevacService
eps.snabdevanje.promenasnabdevaca.mb.MBPromenaSnabdevacaOdlazak ..> eps.snabdevanje.promenasnabdevaca.service.StatusService
eps.snabdevanje.promenasnabdevaca.mb.MBSnabdevac ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.mb.MBSnabdevac ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelSnabdevac
eps.snabdevanje.promenasnabdevaca.mb.MBSnabdevac ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTehnickiCentar
eps.snabdevanje.promenasnabdevaca.mb.MBSnabdevac ..> eps.snabdevanje.promenasnabdevaca.service.SnabdevacService
eps.snabdevanje.promenasnabdevaca.mb.MBStatus ..> eps.snabdevanje.promenasnabdevaca.domen.Status
eps.snabdevanje.promenasnabdevaca.mb.MBStatus ..> eps.snabdevanje.promenasnabdevaca.service.StatusService
eps.snabdevanje.promenasnabdevaca.mb.MBStatusGrupeZahteva ..> eps.snabdevanje.promenasnabdevaca.domen.StatusGrupeZahteva
eps.snabdevanje.promenasnabdevaca.mb.MBStatusGrupeZahteva ..> eps.snabdevanje.promenasnabdevaca.service.StatusGrupeZahtevaService
eps.snabdevanje.promenasnabdevaca.mb.MBTehnickiCentar ..> eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
eps.snabdevanje.promenasnabdevaca.mb.MBTehnickiCentar ..> eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
eps.snabdevanje.promenasnabdevaca.mb.MBTehnickiCentar ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTehnickiCentar
eps.snabdevanje.promenasnabdevaca.mb.MBTehnickiCentar ..> eps.snabdevanje.promenasnabdevaca.service.TehnickiCentarService
eps.snabdevanje.promenasnabdevaca.mb.MBTipDokumenta ..> eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
eps.snabdevanje.promenasnabdevaca.mb.MBTipDokumenta ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelTipDokumenta
eps.snabdevanje.promenasnabdevaca.mb.MBTipDokumenta ..> eps.snabdevanje.promenasnabdevaca.service.TipDokumentaService
eps.snabdevanje.promenasnabdevaca.mb.MBUser ..> eps.snabdevanje.promenasnabdevaca.domen.User
eps.snabdevanje.promenasnabdevaca.mb.MBUser ..> eps.snabdevanje.promenasnabdevaca.lazyViews.LazyDataModelUser
eps.snabdevanje.promenasnabdevaca.mb.MBUser ..> eps.snabdevanje.promenasnabdevaca.service.UserService
eps.snabdevanje.promenasnabdevaca.service.impl.DokumentServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.Dokument
eps.snabdevanje.promenasnabdevaca.service.impl.DokumentServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.DokumentDAO
eps.snabdevanje.promenasnabdevaca.service.impl.DokumentServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.DokumentService
eps.snabdevanje.promenasnabdevaca.service.impl.GrupaZahtevaServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.GrupaZahteva
eps.snabdevanje.promenasnabdevaca.service.impl.GrupaZahtevaServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.GrupaZahtevaDAO
eps.snabdevanje.promenasnabdevaca.service.impl.GrupaZahtevaServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.GrupaZahtevaService
eps.snabdevanje.promenasnabdevaca.service.impl.KupacServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.service.impl.KupacServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.KupacDAO
eps.snabdevanje.promenasnabdevaca.service.impl.KupacServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.KupacService
eps.snabdevanje.promenasnabdevaca.service.impl.MernoMestoServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
eps.snabdevanje.promenasnabdevaca.service.impl.MernoMestoServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.MernoMestoDAO
eps.snabdevanje.promenasnabdevaca.service.impl.MernoMestoServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.MernoMestoService
eps.snabdevanje.promenasnabdevaca.service.impl.PromenaSnabdevacaServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.service.impl.PromenaSnabdevacaServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.PromenaSnabdevacaDAO
eps.snabdevanje.promenasnabdevaca.service.impl.PromenaSnabdevacaServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.PromenaSnabdevacaService
eps.snabdevanje.promenasnabdevaca.service.impl.SnabdevacServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.service.impl.SnabdevacServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.SnabdevacDAO
eps.snabdevanje.promenasnabdevaca.service.impl.SnabdevacServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.SnabdevacService
eps.snabdevanje.promenasnabdevaca.service.impl.StatusGrupeZahtevaImpl ..> eps.snabdevanje.promenasnabdevaca.domen.StatusGrupeZahteva
eps.snabdevanje.promenasnabdevaca.service.impl.StatusGrupeZahtevaImpl ..> eps.snabdevanje.promenasnabdevaca.repository.StatusGrupeZahtevaDAO
eps.snabdevanje.promenasnabdevaca.service.impl.StatusGrupeZahtevaImpl --|> eps.snabdevanje.promenasnabdevaca.service.StatusGrupeZahtevaService
eps.snabdevanje.promenasnabdevaca.service.impl.StatusServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.Status
eps.snabdevanje.promenasnabdevaca.service.impl.StatusServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.StatusDAO
eps.snabdevanje.promenasnabdevaca.service.impl.StatusServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.StatusService
eps.snabdevanje.promenasnabdevaca.service.impl.TehnickiCentarServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
eps.snabdevanje.promenasnabdevaca.service.impl.TehnickiCentarServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.TehnickiCentarDAO
eps.snabdevanje.promenasnabdevaca.service.impl.TehnickiCentarServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.TehnickiCentarService
eps.snabdevanje.promenasnabdevaca.service.impl.TipDokumentaServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
eps.snabdevanje.promenasnabdevaca.service.impl.TipDokumentaServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.TipDokumentaDAO
eps.snabdevanje.promenasnabdevaca.service.impl.TipDokumentaServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.TipDokumentaService
eps.snabdevanje.promenasnabdevaca.service.impl.UserDetailsServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.User
eps.snabdevanje.promenasnabdevaca.service.impl.UserDetailsServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.enumtype.UserRoleEnum
eps.snabdevanje.promenasnabdevaca.service.impl.UserDetailsServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.UserDAO
eps.snabdevanje.promenasnabdevaca.service.impl.UserServiceImpl ..> eps.snabdevanje.promenasnabdevaca.domen.User
eps.snabdevanje.promenasnabdevaca.service.impl.UserServiceImpl ..> eps.snabdevanje.promenasnabdevaca.repository.UserDAO
eps.snabdevanje.promenasnabdevaca.service.impl.UserServiceImpl --|> eps.snabdevanje.promenasnabdevaca.service.UserService
eps.snabdevanje.promenasnabdevaca.repository.DokumentDAO ..> eps.snabdevanje.promenasnabdevaca.domen.Dokument
eps.snabdevanje.promenasnabdevaca.repository.GrupaZahtevaDAO ..> eps.snabdevanje.promenasnabdevaca.domen.GrupaZahteva
eps.snabdevanje.promenasnabdevaca.repository.KupacDAO ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.repository.MernoMestoDAO ..> eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
eps.snabdevanje.promenasnabdevaca.repository.PromenaSnabdevacaDAO ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.repository.SnabdevacDAO ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.repository.StatusDAO ..> eps.snabdevanje.promenasnabdevaca.domen.Status
eps.snabdevanje.promenasnabdevaca.repository.StatusGrupeZahtevaDAO ..> eps.snabdevanje.promenasnabdevaca.domen.StatusGrupeZahteva
eps.snabdevanje.promenasnabdevaca.repository.TehnickiCentarDAO ..> eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
eps.snabdevanje.promenasnabdevaca.repository.TipDokumentaDAO ..> eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
eps.snabdevanje.promenasnabdevaca.repository.UserDAO ..> eps.snabdevanje.promenasnabdevaca.domen.User
eps.snabdevanje.promenasnabdevaca.service.DokumentService ..> eps.snabdevanje.promenasnabdevaca.domen.Dokument
eps.snabdevanje.promenasnabdevaca.service.GrupaZahtevaService ..> eps.snabdevanje.promenasnabdevaca.domen.GrupaZahteva
eps.snabdevanje.promenasnabdevaca.service.KupacService ..> eps.snabdevanje.promenasnabdevaca.domen.Kupac
eps.snabdevanje.promenasnabdevaca.service.MernoMestoService ..> eps.snabdevanje.promenasnabdevaca.domen.MernoMesto
eps.snabdevanje.promenasnabdevaca.service.PromenaSnabdevacaService ..> eps.snabdevanje.promenasnabdevaca.domen.PromenaSnabdevaca
eps.snabdevanje.promenasnabdevaca.service.SnabdevacService ..> eps.snabdevanje.promenasnabdevaca.domen.Snabdevac
eps.snabdevanje.promenasnabdevaca.service.StatusGrupeZahtevaService ..> eps.snabdevanje.promenasnabdevaca.domen.StatusGrupeZahteva
eps.snabdevanje.promenasnabdevaca.service.StatusService ..> eps.snabdevanje.promenasnabdevaca.domen.Status
eps.snabdevanje.promenasnabdevaca.service.TehnickiCentarService ..> eps.snabdevanje.promenasnabdevaca.domen.TehnickiCentar
eps.snabdevanje.promenasnabdevaca.service.TipDokumentaService ..> eps.snabdevanje.promenasnabdevaca.domen.TipDokumenta
eps.snabdevanje.promenasnabdevaca.service.UserService ..> eps.snabdevanje.promenasnabdevaca.domen.User
@enduml